networks:
  monitor:

volumes:
  prometheus-data17: {}
  grafana-data17: {}

services:
  prometheus:
    image: prom/prometheus:v2.31.1
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data17:/prometheus
      - ./rules.yml:/etc/prometheus/rules.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=24h"
      - "--web.enable-lifecycle"
    networks:
      - monitor
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:8.2.4
    restart: unless-stopped
    volumes:
      - grafana-data17:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitor
  alertmanager:
    image: prom/alertmanager:v0.23.0
    restart: unless-stopped
    ports:
      - "9003:9093"
    volumes:
      - "./alertmanager.yml:/config/alertmanager.yml"
    command:
      - "--config.file=/config/alertmanager.yml"
    networks:
      - monitor



