version: "3"
networks:
  devops:
services:
  prod:
    platform: linux/amd64
    image: deadbacteria8/docker-prod:0.0.6
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      SECRET_KEY: ca9c838c110047c0ba1a7750353886b5
      DATABASE_URL: mysql+pymysql://microblog:my-password@mysql/microblog
    container_name: "microblog"
    ports:
      - "8000:5000"
    networks:
      devops:
  db:
    platform: linux/amd64
    image: "mysql:5.7"
    restart: always
    container_name: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: yes
      MYSQL_DATABASE: microblog
      MYSQL_USER: microblog
      MYSQL_PASSWORD: my-password
    ports:
      - "3306:3306"
    volumes:
      - db-data-mysql5:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      timeout: 5s
      retries: 10
    networks:
      devops:
  test:
    restart: always
    image: deadbacteria8/docker-test:1.0.0
    container_name: "microblog_test"
    volumes:
      - ./app:/home/microblog/app
      - ./tests:/home/microblog/tests
    ports:
      - "8001:5001"
    networks:
      devops:
volumes:
  db-data-mysql5: