FROM python:3.8-alpine
WORKDIR /home/microblog
COPY migrations migrations
COPY requirements requirements
COPY microblog.py test.sh Makefile .pylintrc pytest.ini ./
ENV FLASK_APP microblog.py
RUN <<-EOF
    apk add --no-cache make=4.4.1-r2
    adduser -D microblog
    python -m venv .venv
    .venv/bin/pip3 install -r requirements/test.txt
    chmod +x test.sh
    chown -R microblog:microblog ./
EOF

USER microblog
EXPOSE 5001
ENTRYPOINT ["./test.sh"]
