
FROM python:3.12-alpine
WORKDIR /home/microblog
COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py boot.sh ./
ENV FLASK_APP microblog.py
RUN <<-EOF
    adduser -D microblog
    python -m venv .venv
    .venv/bin/pip install --upgrade pip==23.3
    .venv/bin/pip install --upgrade setuptools==70.0.0
    .venv/bin/pip3 install -r requirements.txt
    chmod +x boot.sh
    chown -R microblog:microblog ./
    mkdir /var/log/microblog
    chmod -R 777 /var/log/microblog
EOF

HEALTHCHECK --interval=30s --timeout=10s --start-period=10s --retries=2 \
    CMD curl --fail http://localhost:5000/ || exit 1

USER microblog
EXPOSE 5000
ENTRYPOINT ["sh", "./boot.sh"]
