FROM python:3.10-alpine
WORKDIR /home/microblog
COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py boot.sh ./
ENV FLASK_APP microblog.py
RUN <<-EOF
    adduser -D microblog
    python -m venv .venv
    .venv/bin/pip3 install -r requirements.txt
    chmod +x boot.sh
    chown -R microblog:microblog ./
    mkdir /var/log/microblog
    chmod -R 777 /var/log/microblog
EOF

USER microblog
EXPOSE 5000
ENTRYPOINT ["./boot.sh"]
