# 01-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microblog
spec:
  selector:
    matchLabels:
      app: microblog
  replicas: 2
  template:
    metadata:
      labels:
        app: microblog
    spec:
      containers:
      - image: deadbacteria8/docker-prod:0.0.6
        imagePullPolicy: Always
        name: microblog
        resources:
          requests:
            cou: 250m
          limits:
            cpu: 500m
        ports:
          - containerPort: 5000
        env:
          - name: DATABASE_URL
            value: "mysql+pymysql://microblog:my-super-secret-root-password@mysql/microblog"


#microblog your-password
#my-super-secret-root-password
#my-secret-password